version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:0-7.0
    network_mode: service:seq
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    restart: unless-stopped
    network_mode: service:seq
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - log-data:/data

volumes:
  elasticsearch-data:
  log-data: